# Generated by Django 3.0.7 on 2020-06-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tasks_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task',
            field=models.TextField(null=True),
        ),
    ]
