# Generated by Django 3.0.8 on 2020-08-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200628_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='hackers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('expert_python', models.IntegerField(choices=[(1, '1 - Low'), (2, '2 - Normal'), (3, '3 - Meium'), (4, '4 - High'), (5, '5 - Expert')], null=True)),
                ('expert_dsa', models.IntegerField(choices=[(1, '1 - Low'), (2, '2 - Normal'), (3, '3 - Meium'), (4, '4 - High'), (5, '5 - Expert')], null=True)),
                ('expert_c', models.IntegerField(choices=[(1, '1 - Low'), (2, '2 - Normal'), (3, '3 - Meium'), (4, '4 - High'), (5, '5 - Expert')], null=True)),
                ('expert_django', models.IntegerField(choices=[(1, '1 - Low'), (2, '2 - Normal'), (3, '3 - Meium'), (4, '4 - High'), (5, '5 - Expert')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField()),
                ('voted', models.BooleanField(blank=True, default=False, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hackers')),
            ],
        ),
    ]
