# Generated by Django 3.0.8 on 2020-08-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hackers_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackers',
            name='challenges',
            field=models.IntegerField(null=True),
        ),
    ]
