# Generated by Django 3.0.8 on 2020-08-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_admincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
