# Generated by Django 3.0.8 on 2020-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='ip_addr',
        ),
        migrations.AddField(
            model_name='hackers',
            name='password',
            field=models.CharField(default='pass@123', max_length=30),
        ),
        migrations.AddField(
            model_name='votes',
            name='who_voted',
            field=models.IntegerField(null=True),
        ),
    ]
